### ISSUE TITLE
Vagner - The protocol would not work with BNB like coins that revert on 0 values, even if it is stated that it should work with any coin traded on UniswapV3

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-gfx-judging#24]
Vagner

medium

# The protocol would not work with BNB like coins that revert on 0 values, even if it is stated that it should work with any coin traded on UniswapV3

## Summary
`LimitOrderRegistry.sol` checks after every interaction with the `POSITION_MANAGER` if the allowance is greater than 0 and approves to 0 if that's the case but in the case of BNB this would revert all the time.
## Vulnerability Detail
BNB on ethereum mainnet reverts on every function if the value provided is 0, as you can see here https://etherscan.io/token/0xB8c77482e45F1F44dE1745F52C74426C631bDD52#code#L94 so if the protocol intends to interact with BNB, a token which is supported on UniswapV3 and has a high market cap, this would revert because of how the protocol tries to approve to 0 after `IncreaseLiquidityParams` or `mint` called on `POSITION_MANAGER`.
## Impact
This would have medium impact since some tokens supported on UniswapV3 would not be able to interact with the protocol as it was stated
## Code Snippet
https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1197-L1201
https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1243-L1247
## Tool used

Manual Review

## Recommendation
The easiest way to solve this problem would be to use the `SafeERC20.sol` from OpenZeppelin instead of `SafeTransferLib` from solmate since the big difference between this two is the fact that the safe approve functions from OpenZeppelin always approves to 0, in the case where normal approve reverts so it will solve the problem with tokens that have the Race Condition check into their approve function like USDT https://github.com/OpenZeppelin/openzeppelin-contracts/blob/996168f1f114645b01a1c2e6909c9d98ec451203/contracts/token/ERC20/utils/SafeERC20.sol#L79-L82, so if you use the OpenZeppelin version there is no need to check the allowances after.

**Comment by dugdaniels** [comment]
Escalate for 10 USDC

This should be a marked low/informational as it does not meet the criteria for a medium. There is no attack or loss of funds. The impact, as noted by the watson, is that the protocol simply does not support BNB-like tokens.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> This should be a marked low/informational as it does not meet the criteria for a medium. There is no attack or loss of funds. The impact, as noted by the watson, is that the protocol simply does not support BNB-like tokens.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by VagnerAndrei26** [comment]
Escalate for 10 USDC

I don't agree with the escalation and I'm gonna give some arguments about it :
- first the protocol specified that the ERC20 they are expected to interact with are any ERC20 which is on UniswapV3 pools, BNB it is one of the tokens that is traded on UniswapV3, but would broke the functionality of the protocol
- second, even if funds are not at risk, the whole functionality of the protocol would be broken for the case where one of the pools used, have BNB. To be more specific in the case where minting would not use the whole amount approved and just something between the minAmount and the actual amount, the whole logic of creating new positions would be broken since the function `newOrder` would revert all the time.
So saying all of that I consider it a medium since it can hurt the whole functionality of the protocol in the case where the pool used has BNB, which again is in the scope of the audit since it is traded on UniswapV3, and since it can be solved very easily by the recommendation that I made.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> I don't agree with the escalation and I'm gonna give some arguments about it :
> - first the protocol specified that the ERC20 they are expected to interact with are any ERC20 which is on UniswapV3 pools, BNB it is one of the tokens that is traded on UniswapV3, but would broke the functionality of the protocol
> - second, even if funds are not at risk, the whole functionality of the protocol would be broken for the case where one of the pools used, have BNB. To be more specific in the case where minting would not use the whole amount approved and just something between the minAmount and the actual amount, the whole logic of creating new positions would be broken since the function `newOrder` would revert all the time.
> So saying all of that I consider it a medium since it can hurt the whole functionality of the protocol in the case where the pool used has BNB, which again is in the scope of the audit since it is traded on UniswapV3, and since it can be solved very easily by the recommendation that I made.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by KuTuGu** [comment]
This should be invalid, actually uniswap3 does not support BNB, but WBNB, which has not such restrictions: https://bscscan.com/address/0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c#code

**Comment by VagnerAndrei26** [comment]
@KuTuGu Actually this is not true, UniswapV3 supports BNB and here is an example of a pool of BNB/ETH on the mainnet https://etherscan.io/address/0x9e7809c21ba130c1a51c112928ea6474d9a9ae3c#readContract, as you can see the token0 points to BNB. You are confusing the chains, BNB is not supported on BSC Uniswap because UniswapV3 does not support native tokens by nature, the pools can interact only with their wrapped version, that's why on Mainnet every ETH pool works with WETH and not the native token ETH.

**Comment by xiaoming9090** [comment]
Following are my comments for the judge's consideration:
- From the owner's perspective, having this bug means that Uniswap V3 pool that contains BNB cannot be supported on GFX, while the rest of the Uniswap V3 pools will still work fine.
- From the user's perspective, having this bug means they cannot deposit assets and create a new order within the protocol. Technically, users will not directly lose any funds since they have not deposited any tokens into the protocol yet.

**Comment by VagnerAndrei26** [comment]
To give my last opinion about this issue and to give more context about what I thought:
- I don't see it just as 'not able to interact with the protocol' because the issue is not 100% sure that will happen on the first mint, it can happen, for example, for a position to be minted successfully, since the whole amount allowed by the approve function will be transferred, but it will never be able to `_addToPosition` because some after calculations, some allowance will remain in the contract. All these ***Ifs*** should not be existing in the first place in the protocol since you expect to interact with every token in the UniswapV3 protocol, because they could create bad experiences to the user.
- Since the owner is restricted I assume that the owner of the contract is not someone from GFX protocol, but another person/user, for the case of the owner some amount of funds will be lost, since for a pool to be used the owner needs to call `setupLimitOrder` with the specific pool and pay the upkeep of the pool with LINK tokens, so since he expects every pool of UniswapV3 to be working with the protocol, because that is stated by GFX, he calls `setupLimitOrder` and pays upkeep for a pool that contains BNB, but that whole payment will be useless since the whole functionality of the contract would be broken in that case, so the LINK funds of the owner would be lost.
So considering all of that issues, I think that it should be at least a valid minimum.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the above comments that this is a low impact issue. 
Owner is restricted not to steal funds. There is no loss of funds from not being able to use these tokens. 
Do not need a fair medium issue here

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [dugdaniels](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/24/#issuecomment-1648157859): accepted
- [VagnerAndrei26](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/24/#issuecomment-1648469297): rejected
