### ISSUE TITLE
Vagner - The slippage in `_mintPosition` and `_addToPosition` is hardcoded and too strict which may lead to the protocol being unusable even in low volatility periods

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-gfx-judging#26]
Vagner

medium

# The slippage in `_mintPosition` and `_addToPosition` is hardcoded and too strict which may lead to the protocol being unusable even in low volatility periods

## Summary
The function that increases the liquidity into a UniswapV3 pool uses a hardcoded value of slippage which is set to 0.01% of the amount which can be too low most of the time.
## Vulnerability Detail
The functions that creates new positions or increase the liquidity of a position are `_mintPosition` and `_addToPosition` , both of them calculates the `amount0Min`/`amount1Min` as a hardcoded value, being 99.91% of the `amount0`/`amount1` values https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1226-L1227
https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1172-L1173 
This can have multiple implication but the most important one would be that this slippage value can be too low for most of the pools so any interaction with any of the UniswapV3 pools could not work or revert most of the time, even in some low volatility periods where the values of the pools could change by a little. Consider the fact that even UniswapV3 states that if you use slippage values lower than 0.05% the transaction may revert, their default slippage tolerance being 0.1%.
## Impact
This would have a medium impact since the protocol can be unusable multiple times because of how strict the slippage is.
## Code Snippet
https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1226-L1227
https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1172-L1173
## Tool used

Manual Review

## Recommendation
There are different ways to solve this.

The first one is to let users determine the maximum slippage they're willing to take, the protocol front-end should set the recommended value for them or the second one is have a slippage control parameters that's set by the owner that can be changed anytime. Personally I would suggest the first one since the second one require another person instead of the user.

**Comment by VagnerAndrei26** [comment]
Escalate for 10 USDC.

It was specified in the judge notes that this is a known issue since it is in the README, but the README specifies a different issue from this one which is already invalid. In the README it is specified about `amount0Min` and `amount1Min` in `_takeFromPosition` as can be seen here 
![image](https://github.com/sherlock-audit/2023-06-gfx-judging/assets/111457602/63e41510-c90e-4cbe-a62a-7fe5f1f84739)
The issue that I have talked here is about the hardcoded values in the function `_mintPosition` and `_addToPosition` which are too strict and can make the whole minting mechanic unusable since it only allows for a very low amount of slippage, less than 0.01%. UniswapV3 don't recommend slippages lower than 0.05% since even in periods of low instability the functions would revert.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC.
> 
> It was specified in the judge notes that this is a known issue since it is in the README, but the README specifies a different issue from this one which is already invalid. In the README it is specified about `amount0Min` and `amount1Min` in `_takeFromPosition` as can be seen here 
> ![image](https://github.com/sherlock-audit/2023-06-gfx-judging/assets/111457602/63e41510-c90e-4cbe-a62a-7fe5f1f84739)
> The issue that I have talked here is about the hardcoded values in the function `_mintPosition` and `_addToPosition` which are too strict and can make the whole minting mechanic unusable since it only allows for a very low amount of slippage, less than 0.01%. UniswapV3 don't recommend slippages lower than 0.05% since even in periods of low instability the functions would revert.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by xiaoming9090** [comment]
Escalate for 10 USDC

The purpose of this protocol is to allow users to submit limit orders to Uniswap V3. Under the hood, the protocol will provide a single asset as liquidity within a specific range. When adding liquidity to Uniswap V3, there are two possible scenarios (In the money - ITM OR Out of the money - OTM)

Only when adding liquidity to the current active tick/range will the liquidity provider suffer a slippage. This is because this range is actively trading, and it needs to maintain the current price. However, if someone attempts to submit an order to a current active tick/range, their order will be ITM, and it will be rejected by the following code:

```solidity
OrderStatus status = _getOrderStatus(details.tick, details.lower, details.upper, direction);
// forbid orders that are "ITM". basically, if your order is through the market, then instead of limit order, you should swap
if (status != OrderStatus.OTM) revert LimitOrderRegistry__OrderITM(details.tick, targetTick, direction);
```

Thus, within the protocol, users are only allowed to submit orders to a tick/range that is currently not active. This means that their orders are OTM. In this case, they will not suffer any slippage since they are only "parking" their liquidity at the inactive tick/range, hoping that their limit order will be ITM sometime in the future.

The main reason for the following math is mentioned in the source code's comment. The purpose is to account for rounding errors instead of providing slippage protection. Ideally, the `amount0Min` and `amount1Min` should be 100% of the amount provided when placing a limit order. However, due to precision loss when Solidity executes arithmetic operations, it is not possible to achieve it. Thus, the second best option is to provide a value close to 100%.

```sol
// 0.9999e4 accounts for rounding errors in the Uniswap V3 protocol.
uint128 amount0Min = amount0 == 0 ? 0 : (amount0 * 0.9999e4) / 1e4;
uint128 amount1Min = amount1 == 0 ? 0 : (amount1 * 0.9999e4) / 1e4;
```

In conclusion, the issue is invalid.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> The purpose of this protocol is to allow users to submit limit orders to Uniswap V3. Under the hood, the protocol will provide a single asset as liquidity within a specific range. When adding liquidity to Uniswap V3, there are two possible scenarios (In the money - ITM OR Out of the money - OTM)
> 
> Only when adding liquidity to the current active tick/range will the liquidity provider suffer a slippage. This is because this range is actively trading, and it needs to maintain the current price. However, if someone attempts to submit an order to a current active tick/range, their order will be ITM, and it will be rejected by the following code:
> 
> ```solidity
> OrderStatus status = _getOrderStatus(details.tick, details.lower, details.upper, direction);
> // forbid orders that are "ITM". basically, if your order is through the market, then instead of limit order, you should swap
> if (status != OrderStatus.OTM) revert LimitOrderRegistry__OrderITM(details.tick, targetTick, direction);
> ```
> 
> Thus, within the protocol, users are only allowed to submit orders to a tick/range that is currently not active. This means that their orders are OTM. In this case, they will not suffer any slippage since they are only "parking" their liquidity at the inactive tick/range, hoping that their limit order will be ITM sometime in the future.
> 
> The main reason for the following math is mentioned in the source code's comment. The purpose is to account for rounding errors instead of providing slippage protection. Ideally, the `amount0Min` and `amount1Min` should be 100% of the amount provided when placing a limit order. However, due to precision loss when Solidity executes arithmetic operations, it is not possible to achieve it. Thus, the second best option is to provide a value close to 100%.
> 
> ```sol
> // 0.9999e4 accounts for rounding errors in the Uniswap V3 protocol.
> uint128 amount0Min = amount0 == 0 ? 0 : (amount0 * 0.9999e4) / 1e4;
> uint128 amount1Min = amount1 == 0 ? 0 : (amount1 * 0.9999e4) / 1e4;
> ```
> 
> In conclusion, the issue is invalid.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@VagnerAndrei26 confirming that this a non-issue.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the above escalation

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/26/#issuecomment-1650992402): accepted
- [VagnerAndrei26](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/26/#issuecomment-1648592532): rejected
