### ISSUE TITLE
MohammedRizwan - Solmate safeTransferLib.sol functions does not check the codesize of the token address, which may lead to fund loss

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-gfx-judging#39]
MohammedRizwan

medium

# Solmate safeTransferLib.sol functions does not check the codesize of the token address, which may lead to fund loss

## Summary
Solmate safeTransferLib.sol functions does not check the codesize of the token address, which may lead to fund loss

## Impact

In LimitOrderRegistry.sol contract, Most of the functions have used the safeTransfer() and safeTransferFrom() doesn't check the existence of code at the token address. This is a known issue while using solmate's libraries.

Per the Solmate safeTransferLib.sol,

> Note that none of the functions in this library check that a token has code at all! .....
 
Hence using safeTransferLib.sol library may lead to miscalculation of funds and may lead to loss of funds , **because if safetransfer() and safetransferfrom() are called on a token address that doesn't have contract in it, it will always return success,** bypassing the return value check. Due to this protocol will think that funds has been transferred and successful , and records will be accordingly calculated, but in reality funds were never transferred.

## Code Snippet
https://github.com/crispymangoes/uniswap-v3-limit-orders/blob/753974a4ba5b07ec076c5e5bcbe7277e5921be4b/src/LimitOrderRegistry.sol#L7

https://github.com/crispymangoes/uniswap-v3-limit-orders/blob/753974a4ba5b07ec076c5e5bcbe7277e5921be4b/src/LimitOrderRegistry.sol#L499

https://github.com/crispymangoes/uniswap-v3-limit-orders/blob/753974a4ba5b07ec076c5e5bcbe7277e5921be4b/src/LimitOrderRegistry.sol#L579

https://github.com/crispymangoes/uniswap-v3-limit-orders/blob/753974a4ba5b07ec076c5e5bcbe7277e5921be4b/src/LimitOrderRegistry.sol#L724

https://github.com/crispymangoes/uniswap-v3-limit-orders/blob/753974a4ba5b07ec076c5e5bcbe7277e5921be4b/src/LimitOrderRegistry.sol#L855-L860

## Tool used
Manual Review

## Recommendation
Use openzeppelin's safeERC20 which takes care of token code existence.

**Comment by 0xRizwan** [comment]
Escalate

This is a valid medium issue.

Per the judge comment:

> I think this is low severity issue

**This is a known issue with solmate safeTransferLib.sol and this has been judged as Medium on sherlock in past contest. Refer below references,**

Reference link:- https://github.com/sherlock-audit/2022-11-bond-judging/issues/8

In addition to reference and the report, I would like to add below additional context for its validation,

The issue here is the solmate library does not check the code existence as the functions has used low level .call function.

Per solidity documentation, 

![low level call](https://github.com/sherlock-audit/2023-06-gfx-judging/assets/112799398/0d325650-7893-41ea-a570-a786c3247266)

The Solidity documentation further warns:
**"The low-level functions call, delegatecall and staticcall return true as their first return value if the account called is non-existent, as part of the design of the EVM. Account existence must be checked prior to calling if needed."**

code existence must be checked especially for low level functions like call,staticcall and delegatecall.

Openzeppelin and Solady confirms this and comply this requirements in their library, **only solmate does not check code existence.**

This issue should be taken in consideration based on above report, references and explanation.

Thank you!

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is a valid medium issue.
> 
> Per the judge comment:
> 
> > I think this is low severity issue
> 
> **This is a known issue with solmate safeTransferLib.sol and this has been judged as Medium on sherlock in past contest. Refer below references,**
> 
> Reference link:- https://github.com/sherlock-audit/2022-11-bond-judging/issues/8
> 
> In addition to reference and the report, I would like to add below additional context for its validation,
> 
> The issue here is the solmate library does not check the code existence as the functions has used low level .call function.
> 
> Per solidity documentation, 
> 
> ![low level call](https://github.com/sherlock-audit/2023-06-gfx-judging/assets/112799398/0d325650-7893-41ea-a570-a786c3247266)
> 
> The Solidity documentation further warns:
> **"The low-level functions call, delegatecall and staticcall return true as their first return value if the account called is non-existent, as part of the design of the EVM. Account existence must be checked prior to calling if needed."**
> 
> code existence must be checked especially for low level functions like call,staticcall and delegatecall.
> 
> Openzeppelin and Solady confirms this and comply this requirements in their library, **only solmate does not check code existence.**
> 
> This issue should be taken in consideration based on above report, references and explanation.
> 
> Thank you!

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by VagnerAndrei26** [comment]
Escalate for 10 USDC

I don't believe that this issue is valid since every safeTransfer/safeTransferFrom done in this contract are from tokens that are in UniswapV3 pools, the issue that the Watson provided could be valid if the users could provide any ERC20 address, but in this situation that's not the case.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> I don't believe that this issue is valid since every safeTransfer/safeTransferFrom done in this contract are from tokens that are in UniswapV3 pools, the issue that the Watson provided could be valid if the users could provide any ERC20 address, but in this situation that's not the case. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by xiaoming9090** [comment]
> Escalate for 10 USDC
> 
> I don't believe that this issue is valid since every safeTransfer/safeTransferFrom done in this contract are from tokens that are in UniswapV3 pools, the issue that the Watson provided could be valid if the users could provide any ERC20 address, but in this situation that's not the case.

Agree with this escalation. It will only be an issue if the user could define an arbitrary token address. However, in this case, the token addresses are retrieved directly from the Uniswap Pool contract. Thus, this issue would not happen as it is not possible that the Uniswap Pool is trading with a non-existent token (codesize zero).

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non issue based on above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [VagnerAndrei26](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/39/#issuecomment-1651450288): accepted
- [mohammedrizwann123](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/39/#issuecomment-1651063769): rejected
