### ISSUE TITLE
xiaoming90 - Malicious users could dilute and reduce the fee

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-gfx-judging#49]
xiaoming90

high

# Malicious users could dilute and reduce the fee

## Summary

Malicious users could dilute the `feePerUser` to reduce the fee they must pay when claiming orders. This lead to a loss of assets due to lesser fees being collected for the owner and a loss of opportunity costs for the users.

## Vulnerability Detail

https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1309

```solidity
File: LimitOrderRegistry.sol
1299:     function _fulfillOrder(
1300:         uint256 target,
1301:         UniswapV3Pool pool,
1302:         BatchOrder storage order,
1303:         uint256 estimatedFee,
1304:         uint256 deadline
1305:     ) internal {
1306:         // Save fee per user in Claim Struct.
1307:         uint256 totalUsers = order.userCount;
1308:         Claim storage newClaim = claim[order.batchId];
1309:         newClaim.feePerUser = uint128(estimatedFee / totalUsers);
1310:         newClaim.pool = pool;
..SNIP..
```

As per Line 1309, all users within a batch order share the gas cost for fulfilling the order. The cost is split equally based on the number the users.

However, the problem is that if the minimum asset is not optimal (lower than expected), it will be cost-effective for a malicious user to use multiple different wallet addresses to submit the small order to dilute the `feePerUser`.

Assume the following:

- upkeepGasLimit = 300_000
- upkeepGasPrice = 150
- 1 ETH worth 2000 USD

In this case, the `estimatedFee` for fulfilling each batch order will be computed as follows:

```solidity
estimatedFee = upkeepGasLimit * gasPrice
estimatedFee = 300,000 * 150 Gwei = 45,000,000 Gwei = 0.045 ETH
```

The `estimatedFee` will be `0.045 ETH`, which is worth 90 USD.

If Bob is the only user within the batch order, he has to pay 90 USD worth of ETH all by himself when claiming the order.

If the minimum asset of a new order is set to 5 USDC, Bob could use two unique wallet addresses to create a new order within the same batch order by depositing a minimum sum of 5 USDC. In total, he spent 10 USDC to carry out the attack.

Subseqently, the `estimatedFee` will be divided by 3 users, which results in a `feePerUser` of 30 USD. Thus, when Bob claims his order, he only needs to pay 30 USD instead of 90 USD as a fee (60 USD cheaper)

Bob has no intention of claiming the two small orders that he used for the exploitation. Thus, he will forfeit around 10 USD worth of assets. In addition, he will not be paying 60 USD worth of the fee to the owner since he will not call the `claimOrder` function.

In summary, Bob saved 50 USD (90 - 30 - 10) through this exploit, and the owner lost around 60 USD of the fee.

## Impact

The immediate impact is a loss of assets for the owner due to lesser fees being collected from the users. 

If the losses are significant, it will indirectly affect the owner's ability to replenish the LINK tokens needed to fund the Chainlink Automation. If the LINK tokens were insufficient, the user's orders might not be fulfilled when they are already ITM, potentially leading to a loss of opportunity costs for the users. In addition, since fees are only charged on fulfilled orders, fewer fulfilled orders also mean there will be lesser fees collected.

## Code Snippet

https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1309

## Tool used

Manual Review

## Recommendation

One potential solution is to collect the fee in advance based on the current number of users in a batch order. This should provide a rough estimation of the expected `feePerUser` when the order is fulfilled. When the users claim the order, any excess fee will be refunded, or any deficit will be collected from the users.

This would minimize the owner's loss during an attack. Additionally, it would make the attack unprofitable regardless of the minimum sum configured by the owner, which will benefit users who might not know how to compute the optimal minimum asset for each token to mitigate this risk. 

Also, the optimal minimum asset to mitigate this risk might differ from the optimal minimum asset needed to prevent users from spamming small orders.

**Comment by KuTuGu** [comment]
Escalate
Just as sponsor said, this is a known design problem. The issue relies on minimums being misconfigured, which shouldn't actually happen. This is similar to the problem of admin incorrectly entering parameters and should not be valid.
For the mainnet, the protocol should not set minimums lower than the gas fee, so the assumed 10USDC will not hold.

**Comment by sherlock-admin2** [comment]
> Escalate
> Just as sponsor said, this is a known design problem. The issue relies on minimums being misconfigured, which shouldn't actually happen. This is similar to the problem of admin incorrectly entering parameters and should not be valid.
> For the mainnet, the protocol should not set minimums lower than the gas fee, so the assumed 10USDC will not hold. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by xiaoming9090** [comment]
Escalate for 10 USDC

The fact that malicious users could dilute the `feePerUser` to reduce the fee they must pay when claiming orders is not a known issue or known design problem. It was not mentioned in the Contest Detail page (https://github.com/sherlock-audit/2023-06-gfx#q-please-list-any-known-issuesacceptable-risks-that-should-not-result-in-a-valid-finding) as known issue or previously reported in past audit reports.

We have to look at the root cause or main point of an issue reported, which is not about the admin incorrectly configuring a suboptimal minimum asset. The root cause/main point is due to the way the fee is computed in the current implementation, resulting in malicious users being able to exploit it by using dummy addresses to dilute the fees. And there is a solution that exists that could prevent this issue from happening regardless of the minimum asset being configured, as mentioned in my recommendation. Thus, this issue is valid.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> The fact that malicious users could dilute the `feePerUser` to reduce the fee they must pay when claiming orders is not a known issue or known design problem. It was not mentioned in the Contest Detail page (https://github.com/sherlock-audit/2023-06-gfx#q-please-list-any-known-issuesacceptable-risks-that-should-not-result-in-a-valid-finding) as known issue or previously reported in past audit reports.
> 
> We have to look at the root cause or main point of an issue reported, which is not about the admin incorrectly configuring a suboptimal minimum asset. The root cause/main point is due to the way the fee is computed in the current implementation, resulting in malicious users being able to exploit it by using dummy addresses to dilute the fees. And there is a solution that exists that could prevent this issue from happening regardless of the minimum asset being configured, as mentioned in my recommendation. Thus, this issue is valid.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@KuTuGu

**Comment by KuTuGu** [comment]
Administrators can completely avoid this type of attack by setting a minimum fee greater than the gas fee. This will not be able to share gas costs through multiple users, because the minimum cost is already greater than the average gas cost, and the attacker has more to lose than gain.
There's nothing wrong with what the warden said about diluting fees, which is what the mechanism is designed to do, as long as the administrator sets a minimum fee to avoid attacks while letting the user share the cost of gas.
Among the mitigation measures mentioned by the warden, the agreement charges a fee up front, and the excess will be refunded when the order is collected. I don't think this will mitigate the attack, the attacker can still use a large number of accounts to reduce feePerUser and collect excess funds.

**Comment by xiaoming9090** [comment]
For context, the administrator is RESTRICTED in this contest. As mentioned earlier, the root cause/main point is due to the way the fee is computed in the current implementation, resulting in malicious users being able to exploit it by using dummy addresses to dilute the fees.

As mentioned in the report, if the minimum asset is not optimal (lower than expected), malicious users can exploit the issue. So if the administrator sets the minimum asset below a certain threshold, they will be vulnerable to this bug. 

One of the concerns is that administrator can set the minimum asset to zero or any value. It is difficult for the administrator to know the optimal value to prevent this attack because they are hard to analyze. To prevent the attack entirely, the minimum asset (`minimumAssets`)  must be configured to be larger than the `estimatedFee`.

However, no one would know that they have to set this value unless they have seen this report in the first place because the protocol itself does not implement any control to ensure that the administrator (RESTRICTED) has to set the minimum asset (`minimumAssets`) above the `estimatedFee`.

Also, the real intention of having the `minimumAssets` in the first is not to prevent this attack. Its original intention is to prevent users from spamming a large number of low liquidity orders causing a DOS when the `performUpkeep` function step through the linked list to process the orders. 

Lastly, some administrators of the pools might not want to set the minimum asset (`minimumAssets`) to be larger than `estimatedFee` because it might affect usability as it prevents the benign users from creating small valid orders. So the `minimumAssets` should not be used as a workaround to patch this problem without fixing the root.

**Comment by hrishibhat** [comment]
@xiaoming9090 there are a couple of points I'd like to raise:
- Admin is restricted, but the restriction is that admin should not be able to steal funds. Unlike other issues this is not about admin stealing, So for all other actions, the admin is still trusted. 
- I agree there is no validation for the input and could lead to attack if the value was set below a threshold, but this would still be considered a low based on the point raised above. 
Quoting from the docs:
> As mentioned in the standards observed, in the case of a restricted admin, the restriction must be clearly mentioned for any issue in this category to be considered valid

**Comment by hrishibhat** [comment]
Result:
Low 
Has duplicates
While agreeing that this is not an ideal mechanism,  Considering the impact of this issue a low based on the Sponsor's comment, escalation, and my comments above.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [kutugu](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/49/#issuecomment-1648713560): accepted
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/49/#issuecomment-1650926337): rejected
