### ISSUE TITLE
xiaoming90 - Heartbeat threshold is hardcoded

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-gfx-judging#53]
xiaoming90

medium

# Heartbeat threshold is hardcoded

## Summary

An immutable heartbeat threshold might cause an incorrect staleness check leading to the wrong gas price being computed.

## Vulnerability Detail

https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L229

```solidity
File: LimitOrderRegistry.sol
229:     uint256 public constant FAST_GAS_HEARTBEAT = 7200;
..SNIP..
1447:     function getGasPrice() public view returns (uint256) {
1448:         // If gas feed is set use it.
1449:         if (fastGasFeed != address(0)) {
1450:             (, int256 _answer, , uint256 _timestamp, ) = IChainlinkAggregator(fastGasFeed).latestRoundData();
1451:             uint256 timeSinceLastUpdate = block.timestamp - _timestamp;
1452:             // Check answer is not stale.
1453:             if (timeSinceLastUpdate > FAST_GAS_HEARTBEAT) {
1454:                 // If answer is stale use owner set value.
1455:                 // Multiply by 1e9 to convert gas price to gwei
1456:                 return uint256(upkeepGasPrice) * 1e9;
1457:             } else {
1458:                 // Else use the datafeed value.
1459:                 uint256 answer = uint256(_answer);
1460:                 return answer;
1461:             }
1462:         }
1463:         // Else use owner set value.
1464:         return uint256(upkeepGasPrice) * 1e9; // Multiply by 1e9 to convert gas price to gwei
1465:     }
```

Line 1453 in the above code checks if the value returned from the Chainlink gas feed is stale. If the time last update is larger than `FAST_GAS_HEARTBEAT` (7200 seconds/ 2 hours), then the value is considered stale, and the owner set value will be used.

However, the `FAST_GAS_HEARTBEAT` is hardcoded and immutable. This might be an issue because Chainlink's heartbeat value might be changed in the future. For instance, it might reduce the heartbeat to 3600 seconds (1 hour). If this happen, the existing code will fail to detect the stale value returned from the price feed.

In addition, as per the contest's README, the project is intended to be deployed on multiple L2 chains (Polygon, Optimism, Arbitrum). At the moment, there is no fast gas price feed available on the L2 chains. However, if the fast gas price feed becomes available on L2 chains in the future, the heartbeat of those feeds might not be equal to 7200 seconds.

As mentioned by [Chainlink documentation](https://docs.chain.link/data-feeds):

> Heartbeat and deviation thresholds can also differ for the same asset across different blockchains. 

and existing observation that the heartbeat of price feed across different blockchains are often different (e.g. AAVE/USD on Ethereum - 1 hour heartbeat, AAVE/USD on Arbitrum - 24 hours heartbeat).

In this case, if the owner intended to add L2's fast gas price feed in the future, they will not be able to configure the `FAST_GAS_HEARTBEAT` variable to a different value.

## Impact

Risk of incorrect staleness check leading to the wrong gas price being computed.

## Code Snippet

https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L229

## Tool used

Manual Review

## Recommendation

Consider allowing the owner to update the heartbeat variable in the contract.

**Comment by mstpr** [comment]
Escalate for 10 USDC

According to Sherlock docs this is not a medium finding but a low/informational one. Clearly there are no loss of funds it is only that the gas will be calculated slightly off. 

Also, currently chainlink only supports the fast gas oracle on Mainnet. Arbitrum, Optimism and Polygon does not have a fast gas feed oracle. 

The above examples that the Watson gave was for price feeds not for gas price feeds. As far as I see, the staleness of chainlink price feed is not a valid medium for Sherlock anymore.

In addition to these, there is always the deviation threshold applicable to chainlink price feeds. So the returned value can be stale even though the heartbeat is same.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> According to Sherlock docs this is not a medium finding but a low/informational one. Clearly there are no loss of funds it is only that the gas will be calculated slightly off. 
> 
> Also, currently chainlink only supports the fast gas oracle on Mainnet. Arbitrum, Optimism and Polygon does not have a fast gas feed oracle. 
> 
> The above examples that the Watson gave was for price feeds not for gas price feeds. As far as I see, the staleness of chainlink price feed is not a valid medium for Sherlock anymore.
> 
> In addition to these, there is always the deviation threshold applicable to chainlink price feeds. So the returned value can be stale even though the heartbeat is same.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by xiaoming9090** [comment]
Escalate for 10 USDC

When the gas price is wrong, it will lead to:

- Users pay excessive service fees to the protocol when claiming fulfilled orders; OR
- Owner collecting less fees than expected from the users. The owner would end up making a loss as they cannot recoup the expenses they spend on maintaining the Chainlink automation.

In both cases, it results in a loss of funds for the user or owner. In the second scenario, even a small pricing error will be amplified and lead to significant loss if the `upkeepGasLimit` (fee is computed by multiplying `upkeepGasLimit` by gas price)  is large and/or the `performUpkeep` has been continuously operated for a period of time with the wrong gas pricing causing the loss to accumulate.

The current codebase is intended to be deployed to L2 (arbitrum, optimism, polygon). If L2's fast gas price feed is supported on L2 in the future (which have a reasonable chance of becoming true in the future), and the owner configures the protocol to use the fast gas price feed, they will be stuck with the hardcoded L1 heartbeat value. They will not be able to update the value. Note that the heartbeat value of Chainlink feeds (e.g. gas feed or price feed) might differ across blockchains.

Only Chainlink staleness issue related to Chainlink's round completeness is no longer considered valid because the new OCR does not rely on rounds for reporting as per the https://docs.sherlock.xyz/audits/judging/judging. 

However, this issue is not related to round completeness but related to heartbeat. Stale price issues related to Chainlink's heartbeat have been consistently accepted in past contests (e.g. https://github.com/sherlock-audit/2023-04-jojo-judging/issues/449, https://github.com/sherlock-audit/2023-04-jojo-judging/issues/363, https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/253, https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/83, https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/104). Thus, a Medium would be fair.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> When the gas price is wrong, it will lead to:
> 
> - Users pay excessive service fees to the protocol when claiming fulfilled orders; OR
> - Owner collecting less fees than expected from the users. The owner would end up making a loss as they cannot recoup the expenses they spend on maintaining the Chainlink automation.
> 
> In both cases, it results in a loss of funds for the user or owner. In the second scenario, even a small pricing error will be amplified and lead to significant loss if the `upkeepGasLimit` (fee is computed by multiplying `upkeepGasLimit` by gas price)  is large and/or the `performUpkeep` has been continuously operated for a period of time with the wrong gas pricing causing the loss to accumulate.
> 
> The current codebase is intended to be deployed to L2 (arbitrum, optimism, polygon). If L2's fast gas price feed is supported on L2 in the future (which have a reasonable chance of becoming true in the future), and the owner configures the protocol to use the fast gas price feed, they will be stuck with the hardcoded L1 heartbeat value. They will not be able to update the value. Note that the heartbeat value of Chainlink feeds (e.g. gas feed or price feed) might differ across blockchains.
> 
> Only Chainlink staleness issue related to Chainlink's round completeness is no longer considered valid because the new OCR does not rely on rounds for reporting as per the https://docs.sherlock.xyz/audits/judging/judging. 
> 
> However, this issue is not related to round completeness but related to heartbeat. Stale price issues related to Chainlink's heartbeat have been consistently accepted in past contests (e.g. https://github.com/sherlock-audit/2023-04-jojo-judging/issues/449, https://github.com/sherlock-audit/2023-04-jojo-judging/issues/363, https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/253, https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/83, https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/104). Thus, a Medium would be fair.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@mstpr Do you have additional comments?

**Comment by mstpr** [comment]
@hrishibhat 

Keep in mind that Chainlink's primary aggregator threshold is determined by deviation, not heartbeat. The deviation is currently set to 25%, meaning if there's a 25% difference between the previous and current reports, the aggregator will execute without considering the heartbeat. If the deviation is not triggered, then the heartbeat will be the threshold.

Consider a worst-case scenario with a 24% change that doesn't trigger the deviation. If the fast gas price is 20 Gwei and the current gas price is 17 Gwei, the cost of a Uniswap v3 swap would be $6.09 at 20 Gwei and $5.41 at 17 Gwei. The difference is minor, as seen here. A substantial difference in gas price would trigger the deviation, rendering the heartbeat irrelevant. The maximum potential loss is approximately $2.

The heartbeat is more a time reference than a staleness validator. An incorrect assumption that the heartbeat being 3600 implies that the current code will never be stale, always taking data from Chainlink, is flawed. Problems may arise only if the heartbeat exceeds 7200, leading to a nominal gas cost difference, typically around $0.5.

My research suggests that the heartbeat is hardcoded and unchangeable, though this is not confirmed. If the feed is determined to be stale, the system falls back to a hardcoded value set by the owner. Since owners are likely cognizant of this situation, they can preset a reasonable on-chain value to ensure correct calculations. The feed won't return zero or an incorrect value; it will revert to the owner's reasonable value.

Concerning L2's lack of a fast gas price feed and future assumptions, these are beyond the scope of the current discussion and not valid findings.

In conclusion, this issue is at most a low-severity concern or merely informational. There are no significant potential fund losses, and various safeguards exist, such as trusted owners setting reasonable default gas fees. Therefore, the problem's impact is likely minimal.

**Comment by mstpr** [comment]
Also, above issues that Watson linked are not relevant with this finding and actually indeed proves that this is correctly implemented. There is only 1 fast gas price feed at the moment which is for Ethereum mainnet and the code is adjusted to that and works properly. Future assumptions of L2's should not be a valid finding for Sherlock.

**Comment by hrishibhat** [comment]
Result:
Low
Unique 
While this could be argued to be in the low-medium range, after considering the impact described in the above comments, this can be seen as a  low issue. 
Also the previous issues seem to have a different context than this one as they are not related to the gasprice and have a different impact.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/53/#issuecomment-1650077766): accepted
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/53/#issuecomment-1650924690): rejected

**Comment by elee1766** [comment]
https://github.com/gfx-labs/uniswap-v3-limit-orders/pull/1

**Comment by elee1766** [comment]
fix

**Comment by xiaoming9090** [comment]
Verified. Fixed in https://github.com/gfx-labs/uniswap-v3-limit-orders/pull/1
