### ISSUE TITLE
mstpr-brainbot - Gas limit and gas price is not operable with L2's

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-gfx-judging#7]
mstpr-brainbot

high

# Gas limit and gas price is not operable with L2's

## Summary
Constant gas limit and gas price are not operable with L2's.
## Vulnerability Detail
Max gas limit and gas price are hardcoded as constants in the contracts bytecode meaning that they can't change. However, these values are not operable with Arbitrum. 

Here a random tx found in arbitrum
https://arbiscan.io/tx/0xad0670e42f29ca4a7457b970601df558b5e352c2fe4fba4de8ac8aa9047e3d71

as noticed, the gas limit higher than the contracts constant values.
## Impact
https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L212-L218
## Tool used

Manual Review

**Comment by mstpr** [comment]
Escalate for 10 USDC

This is a valid high. Arbitrum gas limit and gas price doesn't follow the classic EVM structure. In the excel sheet the reason for this to excluded as follows:
"I don't see the problem with the gas limit https://docs.chain.link/chainlink-automation/supported-networks/#configurations"
The provided link states the check gas limit is 6.5M and perform is 5M. However the current code hardcodes the gas limit as 750K. If you can check some random blocks in arbitrum you will see almost every tx has more than 750K limit due to how arbitrum l2 works. 
 Typically the minimum gas limit for an arbitrum tx is 500K (plain ether transfer) considering that keepers will not be able to perform due to gas limit low.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> This is a valid high. Arbitrum gas limit and gas price doesn't follow the classic EVM structure. In the excel sheet the reason for this to excluded as follows:
> "I don't see the problem with the gas limit https://docs.chain.link/chainlink-automation/supported-networks/#configurations"
> The provided link states the check gas limit is 6.5M and perform is 5M. However the current code hardcodes the gas limit as 750K. If you can check some random blocks in arbitrum you will see almost every tx has more than 750K limit due to how arbitrum l2 works. 
>  Typically the minimum gas limit for an arbitrum tx is 500K (plain ether transfer) considering that keepers will not be able to perform due to gas limit low. 
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by xiaoming9090** [comment]
Escalate for 10 USDC

Arbitrum is EVM-compatible. The gas required to execute a transaction is the same on Arbitrum and Ethereum per Arbitrum's documentation. So the amount of gas required to execute the `performUpkeep` function would be around the same.

> It works the same as Ethereum gas, in the sense that every EVM instruction costs the same amount of gas that it would on Ethereum.
>
> Taken from https://developer.arbitrum.io/inside-arbitrum-nitro/#gas-and-fees

Note that the gasLimit of the upkeep is set to `maxFillsPerUpkeep * upkeepGasLimit`, not only `upkeepGasLimit`.

```solidity
// Use V2 Upkeep Registration.
ERC20(address(LINK)).safeApprove(address(registrar), initialUpkeepFunds); // @audit-ok
RegistrationParams memory params = RegistrationParams({
    name: "Limit Order Registry",
    encryptedEmail: abi.encode(0),
    upkeepContract: address(this),
    gasLimit: uint32(maxFillsPerUpkeep * upkeepGasLimit),
```

Assume the `maxFillsPerUpkeep` is 4 and the `upkeepGasLimit` is set to the maximum of `750_000`, then the keeper would have a gas limit of up to `3,000,000` to trigger the `performUpkeep` function. 3 million is below the 5 million Perform Gas Limit in Chainlink. 

The purpose of the gas limit is to allow the keeper to use up to 3,000,000 gas when calling the `performUpkeep` function. The low gas limit error might only occur if the keeper's gasLimit is set to below 21000, but the default setting in the contract is already set at 300000. So I don't see any issue here.

**Comment by mstpr** [comment]
owner takes the fee as 
`uint256 estimatedFee = uint256(upkeepGasLimit * getGasPrice());`
so the assumption here is that the gas limit (max 750K) * gasPrice will be the fee for the owner. However, even though the loop runs only once the gas limit is above 750K hence, the owner always takes lesser fees than it should even with the maximum gas limit set. 

Also about the gas price, the gas price minimum value is 1Gwei and max value is 1000Gwei. In rollups like Arbitrum and Optimism the gas price is usually 0.1-0.001 Gwei. That means it is not adaptable for these chains which are in the scope.

Also, if the loop is called with 3-4 iterations the gas limit needs to perform the function is higher than the cap of chainlink (5M). I will try to provide some PoC here 

There are few things to do to mitigate these things:

1- Owner creates a mock oracle contract and returns the gas price as 0.001-0.1 Gwei, the correct gas price. Since chainlink gas feed is not existed in Arbitrum that's why the owner needs to create a mock contract. 

2- Owner sets the gas limit to 750K when adding a new pool such that the keeper gas limit is correctly set (something near 5M needed). Then immediately owner sets it to a value like 100-1K and sets the gas price to something like 1-100 such that the multiplication of gas price and gas used is a realistic value for L2's.

As we can see both of the solutions are quite custom and most likely the protocol team didn't know about it. If the code deployed to Arbitrum with the initial values, (300K gas limit, 30 gas price and 10 upkeep) the chainlink keeper maximum gas limit would be 3M (which is not enough for filling 10 upkeeps in Arbitrum) and the gas fee that taken from the user is 300 * 30 Gwei = 0.009 ETH == 18$ for per iteration. Which clearly is extremely over priced for L2's.

**Comment by mstpr** [comment]
to response your statement @xiaoming9090 

In your case the maximum limit is 3M which is even smaller than the max cap of Chainlink (5M). If the performUpkeep exceeds 3M gas keepers will not be able to call the function. Uniswap collect+decreaseLiquidity actions mostly takes 1.5M gas. Since this function does more storage operations inside the contract in addition to uniswap integration the gas limit can easily exceed 3M.

**Comment by cvetanovv** [comment]
In the report, you give example how MAX_GAS_LIMIT can be at most 750_000 and this is "not operable with Arbitrum". 
Then xiaoming gives a good example how to calculate the gasLimit of the upkeep: `maxFillsPerUpkeep * upkeepGasLimit`.

https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L407
https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L422

But his example is `maxFillsPerUpkeep = 4`. But it could be much more. A maxFillsPerUpkeep can even be 20:
https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L223

And here it settles at any time:
https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L379-L382
That is, the gas limit can be up to 15 million and not up to 750,000 as written. So in my opinion this is an invalid issue.

**Comment by mstpr** [comment]
> In the report, you give example how MAX_GAS_LIMIT can be at most 750_000 and this is "not operable with Arbitrum". Then xiaoming gives a good example how to calculate the gasLimit of the upkeep: `maxFillsPerUpkeep * upkeepGasLimit`.
> 
> https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L407 https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L422
> 
> But his example is `maxFillsPerUpkeep = 4`. But it could be much more. A maxFillsPerUpkeep can even be 20: https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L223
> 
> And here it settles at any time: https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L379-L382 That is, the gas limit can be up to 15 million and not up to 750,000 as written. So in my opinion this is an invalid issue.

and then how are you going to take the fee? 
https://github.com/sherlock-audit/2023-06-gfx/blob/59a83c6423834b9173b9c063ec1e505c5d9f1bbb/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L925

750K * 1 Gwei (minimum can be set) = 0.00075 ETH == 1.5$ for single upkeep, which is way over priced again.

**Comment by mstpr** [comment]
> owner takes the fee as `uint256 estimatedFee = uint256(upkeepGasLimit * getGasPrice());` so the assumption here is that the gas limit (max 750K) * gasPrice will be the fee for the owner. However, even though the loop runs only once the gas limit is above 750K hence, the owner always takes lesser fees than it should even with the maximum gas limit set.
> 
> Also about the gas price, the gas price minimum value is 1Gwei and max value is 1000Gwei. In rollups like Arbitrum and Optimism the gas price is usually 0.1-0.001 Gwei. That means it is not adaptable for these chains which are in the scope.
> 
> Also, if the loop is called with 3-4 iterations the gas limit needs to perform the function is higher than the cap of chainlink (5M). I will try to provide some PoC here
> 
> There are few things to do to mitigate these things:
> 
> 1- Owner creates a mock oracle contract and returns the gas price as 0.001-0.1 Gwei, the correct gas price. Since chainlink gas feed is not existed in Arbitrum that's why the owner needs to create a mock contract.
> 
> 2- Owner sets the gas limit to 750K when adding a new pool such that the keeper gas limit is correctly set (something near 5M needed). Then immediately owner sets it to a value like 100-1K and sets the gas price to something like 1-100 such that the multiplication of gas price and gas used is a realistic value for L2's.
> 
> As we can see both of the solutions are quite custom and most likely the protocol team didn't know about it. If the code deployed to Arbitrum with the initial values, (300K gas limit, 30 gas price and 10 upkeep) the chainlink keeper maximum gas limit would be 3M (which is not enough for filling 10 upkeeps in Arbitrum) and the gas fee that taken from the user is 300 * 30 Gwei = 0.009 ETH == 18$ for per iteration. Which clearly is extremely over priced for L2's.

@cvetanovv  in here I explained how to avoid the issue. However, this is clearly a very custom solution and I doubt protocol team knew about it

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with Lead Watsona and Lead judge comments above:
https://github.com/sherlock-audit/2023-06-gfx-judging/issues/7#issuecomment-1681833547
These comments address the points in the original issue raised

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/7/#issuecomment-1648351607): rejected
